### ISSUE TITLE
Python-3.8+ support?

### ISSUE THREAD

**Issue by juippis** [wimmuskee/gengee#8]
Hey, 

tried to run this today. Got: 
```
Traceback (most recent call last):
  File "./gengee-update", line 5, in <module>
    from gengee.portage import *
  File "/home/joonas/bin/gengee/gengee/portage.py", line 4, in <module>
    import portage
ModuleNotFoundError: No module named 'portage'
```

I've already migrated to python3.8 system-wide, does this has something to do with it?
```
[ebuild   R    ] sys-apps/portage-2.3.103::gentoo  USE="gentoo-dev (ipc) native-extensions xattr -apidoc -build -doc -rsync-verify (-selinux)" PYTHON_TARGETS="python3_8 -pypy3 -python3_6 -python3_7 -python3_9"

[ebuild   R    ] dev-python/PyGithub-1.51::gentoo  USE="-test" PYTHON_TARGETS="python3_8 -python3_6 -python3_7 -python3_9%" 0 KiB
[ebuild   R    ] dev-python/prettytable-0.7.2-r1::gentoo  USE="-test" PYTHON_TARGETS="python3_8 -python2_7 -python3_6 -python3_7 -python3_9%" 0 KiB
[ebuild   R    ] dev-python/requests-2.24.0::gentoo  USE="ssl -socks5 -test" PYTHON_TARGETS="python3_8 -pypy3 -python2_7 -python3_6 -python3_7 -python3_9" 0 KiB
```

**Comment by juippis** [comment]
Ok so this was due to my system setting, manually editing shebang to point to python3.8 works. I looked at your ebuild and it's still in 3.7 so I **assumed** it doesn't work with later ones yet.

**Comment by wimmuskee** [comment]
it works with py3.8, just updated ebuild
